// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_path_ from "./routes/[...path].tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $health from "./routes/health.tsx";
import * as $ping from "./routes/ping.tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[...path].tsx": $_path_,
    "./routes/_middleware.ts": $_middleware,
    "./routes/health.tsx": $health,
    "./routes/ping.tsx": $ping,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
